name: mini_naplo
description: Modern E-diary.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # animated ui libs
  rive: ^0.10.2
  flutter_svg: ^2.0.1
  animations: ^2.0.7
  # for charts
  #fl_chart: ^0.61.0
  syncfusion_flutter_charts: ^20.4.51
  # for api and encoding 
  http: ^0.13.3
  crypto: ^3.0.2
  intl: ^0.18.0
  # database
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  # state / route manager  
  get: ^4.6.5
  # internet status
  connectivity_plus: ^3.0.3
  # refresh pull 
  liquid_pull_to_refresh: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/launcher.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/timetable/
    - assets/images/login/
    - assets/animated_images/rive/
    - assets/animated_icons/
    - assets/Fonts/
    
    # iconpaths
    - assets/3dicons/gym/
    - assets/3dicons/calculator/
    - assets/3dicons/painting-kit/
    - assets/3dicons/computer/
    - assets/3dicons/flag/
    - assets/3dicons/notebook/
    - assets/3dicons/battery/
    - assets/3dicons/calender/
    - assets/3dicons/hash/
    - assets/3dicons/picture/
    - assets/3dicons/pencil/
    - assets/3dicons/setting/
    - assets/3dicons/thumb-down/
    - assets/3dicons/cube/
    - assets/3dicons/picture/
    - assets/3dicons/boy/
    - assets/3dicons/tools/
    - assets/3dicons/heart/
    - assets/3dicons/file/
    - assets/3dicons/file-text/    
    - assets/3dicons/text/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700